// Sommarlovsbingo challenges
// ⚽ = fotboll/idrott   ☀️ = sommar
export const BINGO = [
  // FOTBOLL & IDROTT (35 st)
  { id: "b01", cat: "⚽", label: "Slå 10 straffar med höger fot", points: 30 },
  { id: "b02", cat: "⚽", label: "Slå 10 straffar med vänster fot", points: 30 },
  { id: "b03", cat: "⚽", label: "Träna på att jonglera i 20 minuter (totalt)", points: 40 },
  { id: "b04", cat: "⚽", label: "Stå i mål och gör 10 räddningar", points: 35 },
  { id: "b05", cat: "⚽", label: "Träffa ribban 5 gånger", points: 45 },
  { id: "b06", cat: "⚽", label: "Passa 100 passningar med någon", points: 35 },
  { id: "b07", cat: "⚽", label: "Öva in en målgest", points: 15 },
  { id: "b08", cat: "⚽", label: "Kom på en ny hejaramsa till laget", points: 25 },
  { id: "b09", cat: "⚽", label: "Se en hel VM-match utan att scrolla", points: 30 },
  { id: "b10", cat: "⚽", label: "Kasta upp bollen högt och ta emot den med foten 10 gånger", points: 20 },
  { id: "b11", cat: "⚽", label: "Gör 50 toe taps utan paus", points: 30 },
  { id: "b12", cat: "⚽", label: "Gör 50 tvåfotare utan paus", points: 30 },
  { id: "b13", cat: "⚽", label: "Jonglera 5 gånger i rad", points: 30 },
  { id: "b14", cat: "⚽", label: "Spela fotboll barfota i sand", points: 20 },
  { id: "b15", cat: "⚽", label: "Gör en Cruyff-fint 20 gånger", points: 30 },
  { id: "b16", cat: "⚽", label: "Skjut 10 volleyskott", points: 25 },
  { id: "b17", cat: "⚽", label: "Skjut 20 skott mot mål", points: 25 },
  { id: "b18", cat: "⚽", label: "Spela fotboll utomhus i 1 timme", points: 40 },
  { id: "b19", cat: "⚽", label: "Träna med en kompis", points: 25 },
  { id: "b20", cat: "⚽", label: "Stå på höger ben i minst 1 minut", points: 20 },
  { id: "b21", cat: "⚽", label: "Stå på vänster ben i minst 1 minut", points: 20 },
  { id: "b22", cat: "⚽", label: "Gör plankan i 45 sekunder", points: 30 },
  { id: "b23", cat: "⚽", label: "Gör 10 benböj, 10 utfallssteg, 10 upphop", points: 30 },
  { id: "b24", cat: "⚽", label: "Jogga 2 km med en vuxen", points: 35 },
  { id: "b25", cat: "⚽", label: "Gör 10 kullerbyttor", points: 20 },
  { id: "b26", cat: "⚽", label: "Spela en match med andra", points: 40 },
  { id: "b27", cat: "⚽", label: "Lär dig en valfri fint", points: 25 },
  { id: "b28", cat: "⚽", label: "Testa att spela med bara ”fel fot” i 10 min", points: 30 },
  { id: "b29", cat: "⚽", label: "Öva på att kasta så långa inkast du kan 20 st", points: 30 },
  { id: "b30", cat: "⚽", label: "Gör 100 hopp med hopprep", points: 25 },
  { id: "b31", cat: "⚽", label: "Balansera bollen på foten i 10 sekunder", points: 35 },
  { id: "b32", cat: "⚽", label: "Spela fotboll barfota i gräs", points: 20 },
  { id: "b33", cat: "⚽", label: "Lär dig namn och position på 6 spelare i damlandslaget", points: 25 },
  { id: "b34", cat: "⚽", label: "Gå till Långholmens IP och spela fotboll", points: 30 },
  { id: "b35", cat: "⚽", label: "Träna fotboll mot en vägg i 30 minuter", points: 30 },
  // SOMMAR (15 st)
  { id: "b36", cat: "☀️", label: "Bada 3 gånger på en dag", points: 25 },
  { id: "b37", cat: "☀️", label: "Plocka ett strå med smultron", points: 20 },
  { id: "b38", cat: "☀️", label: "Plantera något (blomma, grönsak, frö…)", points: 25 },
  { id: "b39", cat: "☀️", label: "Läs en bok (minst 50 sidor)", points: 25 },
  { id: "b40", cat: "☀️", label: "Ät en glass", points: 15 },
  { id: "b41", cat: "☀️", label: "Cykla på en grusväg", points: 20 },
  { id: "b42", cat: "☀️", label: "Sov utomhus (tält, hängmatta, trappa…)", points: 30 },
  { id: "b43", cat: "☀️", label: "Hitta och titta på ett vilt djur i naturen", points: 15 },
  { id: "b44", cat: "☀️", label: "Hjälp till att laga mat", points: 20 },
  { id: "b45", cat: "☀️", label: "Skriv ett brev eller vykort till någon", points: 25 },
  { id: "b46", cat: "☀️", label: "Titta på solnedgången", points: 15 },
  { id: "b47", cat: "☀️", label: "Bygg något med händerna (Lego, sandborg, trä…)", points: 20 },
  { id: "b48", cat: "☀️", label: "Laga mat eller baka något från grunden", points: 30 },
  { id: "b49", cat: "☀️", label: "Gör något snällt för någon utan att berätta det", points: 25 },
  { id: "b50", cat: "☀️", label: "Ha picknick utomhus", points: 20 },
];

// Daily & Weekly Challenges
export const DAILY_CHALLENGES = [
  // Bollkontroll & teknik (30 st)
  { id: "d01", label: "Ta emot 20 kastade bollar med insidan av foten", points: 20, icon: "🦶" },
  { id: "d02", label: "Jonglera bollen 4 gånger utan att nudda marken", points: 20, icon: "⚽" },
  { id: "d03", label: "Gör 50 toe taps utan paus", points: 20, icon: "👟" },
  { id: "d04", label: "Håll bollen stilla på foten i 5 sekunder", points: 25, icon: "⚽" },
  { id: "d05", label: "Gör 25 tvåfotare utan att tappa bollen", points: 20, icon: "🦶" },
  { id: "d06", label: "Jonglera bollen 3 gånger med knät", points: 20, icon: "⚽" },
  { id: "d07", label: "Dribbla runt ett föremål 5 gånger med vänsterfoten", points: 20, icon: "🌀" },
  { id: "d08", label: "Gör 10 suldrag med höger och 10 med vänster fot", points: 20, icon: "👟" },
  { id: "d09", label: "Passa bollen mot en vägg i 15 minuter", points: 20, icon: "🏃" },
  { id: "d10", label: "Stoppa 20 bollar med sulan när någon rullar mot dig", points: 20, icon: "🦶" },
  { id: "d11", label: "Gör en Cruyff-fint 15 gånger i rad", points: 20, icon: "✨" },
  { id: "d12", label: "Ta emot 20 kastade bollar med knät", points: 20, icon: "⚽" },
  { id: "d13", label: "Skjut 20 skott och försök träffa ett mål eller en vägg", points: 20, icon: "🥅" },
  { id: "d14", label: "Dribla bollen med insidan fram och tillbaka 10 ggr", points: 20, icon: "🌀" },
  { id: "d15", label: "Driv bollen i en åtta runt två föremål i 3 minuter", points: 20, icon: "🌀" },
  { id: "d16", label: "Gör 10 vändningar med insidan och 10 med utsidan av foten", points: 20, icon: "👟" },
  { id: "d17", label: "Gör 15 passningar mot en vägg/kompis med ”fel” fot", points: 20, icon: "🏃" },
  { id: "d18", label: "Håll bollen i luften med axeln 3 gånger", points: 25, icon: "⚽" },
  { id: "d19", label: "Gör 20 toe taps med enbart vänsterfoten", points: 20, icon: "👟" },
  { id: "d20", label: "Kasta/skjut bollen mot en vägg och ta emot med bröstet", points: 25, icon: "🏃" },
  { id: "d21", label: "Stå på ett ben så länge du kan!", points: 20, icon: "🦶" },
  { id: "d22", label: "Gör en fint och skjut — 5 gånger", points: 20, icon: "🥅" },
  { id: "d23", label: "Gör en hinderbana och dribbla runt utan att tappa bollen", points: 20, icon: "🌀" },
  { id: "d24", label: "Jonglera bollen 2 gånger med huvudet", points: 25, icon: "⚽" },
  { id: "d25", label: "Gör 25 passningar med insidan av foten mot en vägg", points: 20, icon: "🏃" },
  { id: "d26", label: "Skjut 20 skott och försök träffa i ett hörn", points: 25, icon: "🥅" },
  { id: "d27", label: "Kasta upp bollen högt och ta emot den med foten 10 gånger", points: 20, icon: "⚽" },
  { id: "d28", label: "Passa 30 gånger mot vägg utan att bollen stannar helt", points: 20, icon: "🏃" },
  { id: "d29", label: "Spela Rondo med 4 andra", points: 30, icon: "🤝" },
  { id: "d30", label: "Balansera bollen på foten och gå 3 steg", points: 30, icon: "⚽" },
  // Kondition & rörlighet (20 st)
  { id: "d31", label: "Gå ut och spring så långt du orkar", points: 20, icon: "🏃" },
  { id: "d32", label: "Gör 15 utfallssteg med bollen i händerna", points: 20, icon: "💪" },
  { id: "d33", label: "Hoppa hopprep i 1 minut", points: 20, icon: "💫" },
  { id: "d34", label: "Gör 10 benböj och 10 armhävningar", points: 20, icon: "💪" },
  { id: "d35", label: "Stå i plankan i 30 sekunder", points: 20, icon: "💪" },
  { id: "d36", label: "Gör 20 höga knän på stället i 30 sekunder", points: 20, icon: "🏃" },
  { id: "d37", label: "Stretcha benen ordentligt i 5 minuter", points: 15, icon: "🧘" },
  { id: "d38", label: "Gör 10 kullerbyttor", points: 15, icon: "🌀" },
  { id: "d39", label: "Stå på ett ben i 45 sekunder utan att nudda marken", points: 20, icon: "🦶" },
  { id: "d40", label: "Gör 20 hopp på ett ben — höger och vänster", points: 20, icon: "💫" },
  { id: "d41", label: "Gör 10 situps, tre gånger!", points: 20, icon: "💪" },
  { id: "d42", label: "Gör 15 armhävningar", points: 20, icon: "💪" },
  { id: "d43", label: "Hitta en backe och spring upp, gå ner, 10 ggr", points: 35, icon: "🏃" },
  { id: "d44", label: "Gör 30 jumping jacks", points: 15, icon: "💫" },
  { id: "d45", label: "Spring baklänges fram och tillbaka över en fotbollsplan, 6 ggr", points: 25, icon: "🏃" },
  { id: "d46", label: "Gör 10 utfallssteg framåt och 10 bakåt", points: 20, icon: "💪" },
  { id: "d47", label: "Hoppa över ett föremål, fram och tillbaka 20 gånger", points: 20, icon: "💫" },
  { id: "d48", label: "Balansera på ett ben med ögonen stängda i 20 sek", points: 25, icon: "🧘" },
  { id: "d49", label: "Gör 5 minuters uppvärmning: springa, hopp och stretch", points: 20, icon: "🏃" },
  { id: "d50", label: "Ta en 10-minuters promenad med fotbollen under armen", points: 15, icon: "🌿" },
  // Roliga/kreativa (20 st)
  { id: "d51", label: "Hitta på ett eget tricks och visa det för någon", points: 25, icon: "🌟" },
  { id: "d52", label: "Spela fotboll barfota på gräs", points: 20, icon: "🌿" },
  { id: "d53", label: "Öva in en målgest", points: 15, icon: "🎉" },
  { id: "d54", label: "Sjung lagets hejaramsa högt tre gånger", points: 15, icon: "📣" },
  { id: "d55", label: "Spela fotboll med någon du inte känner", points: 25, icon: "🤝" },
  { id: "d56", label: "Skjut en straff med ögonen stängda", points: 25, icon: "🥅" },
  { id: "d57", label: "Skapa en hinderbana och dribbla igenom den", points: 20, icon: "🌀" },
  { id: "d58", label: "Träna med någon annan i 15 minuter", points: 20, icon: "🤝" },
  { id: "d59", label: "Filma dig själv och titta på en övning du gjort", points: 20, icon: "📱" },
  { id: "d60", label: "Berätta för någon vad du tränat idag", points: 15, icon: "💬" },
  { id: "d61", label: "Sätt upp ett mål för nästa säsong och skriv ned det", points: 15, icon: "📝" },
  { id: "d62", label: "Prova att jonglera med en tennisboll", points: 25, icon: "⚽" },
  { id: "d63", label: "Spela fotboll mot en vägg i 10 minuter", points: 20, icon: "🏃" },
  { id: "d64", label: "Passa med någon och se hur många passningar ni kan slå utan att tappa bollen", points: 20, icon: "🤝" },
  { id: "d65", label: "Lek kasta gris med någon/några andra", points: 20, icon: "🎯" },
  { id: "d66", label: "Lek ”håll den uppe” med en ballong inomhus", points: 15, icon: "🎈" },
  { id: "d67", label: "Ta 10 foton av din boll på roliga ställen", points: 15, icon: "📸" },
  { id: "d68", label: "Hitta på en ny övning och lär ut den till en vuxen", points: 25, icon: "💡" },
  { id: "d69", label: "Gör 10 skott med höger och 10 med vänsterfoten", points: 20, icon: "🥅" },
  { id: "d70", label: "Öva på att göra en ”Rainbow flick” i 20 min", points: 30, icon: "🌈" },
];

// Weekly challenges — team goals based on week number
// Each week alternates between touch-heavy and minutes-heavy
export const WEEKLY_CHALLENGES = [
  { id: "w01", label: "Jonas utmanar er: 2800 touch tillsammans den här veckan", type: "touch", goal: 2800, points: 50 },
  { id: "w02", label: "190 minuters träning tillsammans den här veckan", type: "minutes", goal: 190, points: 50 },
  { id: "w03", label: "Calle utmanar er: 3000 touch tillsammans den här veckan", type: "touch", goal: 3000, points: 60 },
  { id: "w04", label: "210 minuters träning tillsammans den här veckan", type: "minutes", goal: 210, points: 60 },
  { id: "w05", label: "Jakob utmanar er: 3200 touch tillsammans den här veckan", type: "touch", goal: 3200, points: 70 },
  { id: "w06", label: "230 minuters träning tillsammans den här veckan", type: "minutes", goal: 230, points: 70 },
  { id: "w07", label: "Richard utmanar er: 3400 touch tillsammans den här veckan", type: "touch", goal: 3400, points: 75 },
  { id: "w08", label: "250 minuters träning tillsammans den här veckan", type: "minutes", goal: 250, points: 75 },
  { id: "w09", label: "Peter utmanar er: 3600 touch tillsammans den här veckan", type: "touch", goal: 3600, points: 80 },
  { id: "w10", label: "270 minuters träning tillsammans den här veckan", type: "minutes", goal: 270, points: 80 },
  { id: "w11", label: "Jonas utmanar er igen: 3800 touch tillsammans den här veckan", type: "touch", goal: 3800, points: 90 },
  { id: "w12", label: "290 minuters träning tillsammans den här veckan", type: "minutes", goal: 290, points: 90 },
];
