// Sommarlovsbingo challenges
// ⚽ = fotboll/idrott   ☀️ = sommar
import type { BingoTile, DailyChallenge, WeeklyChallenge } from '../types';

export const BINGO: BingoTile[] = [
  // FOTBOLL & IDROTT (35 st)
  { id: 'b01', cat: '⚽', label: 'Slå 10 straffar med höger fot', points: 30 },
  { id: 'b02', cat: '⚽', label: 'Slå 10 straffar med vänster fot', points: 30 },
  { id: 'b03', cat: '⚽', label: 'Träna på att jonglera i 20 minuter (totalt)', points: 40 },
  { id: 'b04', cat: '⚽', label: 'Stå i mål och gör 10 räddningar', points: 35 },
  { id: 'b05', cat: '⚽', label: 'Träffa ribban 5 gånger', points: 45 },
  { id: 'b06', cat: '⚽', label: 'Passa 100 passningar med någon', points: 35 },
  { id: 'b07', cat: '⚽', label: 'Öva in en målgest', points: 15 },
  { id: 'b08', cat: '⚽', label: 'Kom på en ny hejaramsa till laget', points: 25 },
  { id: 'b09', cat: '⚽', label: 'Se en hel VM-match utan att scrolla', points: 30 },
  {
    id: 'b10',
    cat: '⚽',
    label: 'Kasta upp bollen högt och ta emot den med foten 10 gånger',
    points: 20,
  },
  { id: 'b11', cat: '⚽', label: 'Gör 50 toe taps utan paus', points: 30 },
  { id: 'b12', cat: '⚽', label: 'Gör 50 tvåfotare utan paus', points: 30 },
  { id: 'b13', cat: '⚽', label: 'Jonglera 5 gånger i rad', points: 30 },
  { id: 'b14', cat: '⚽', label: 'Spela fotboll barfota i sand', points: 20 },
  { id: 'b15', cat: '⚽', label: 'Gör en Cruyff-fint 20 gånger', points: 30 },
  { id: 'b16', cat: '⚽', label: 'Skjut 10 volleyskott', points: 25 },
  { id: 'b17', cat: '⚽', label: 'Skjut 20 skott mot mål', points: 25 },
  { id: 'b18', cat: '⚽', label: 'Spela fotboll utomhus i 1 timme', points: 40 },
  { id: 'b19', cat: '⚽', label: 'Träna med en kompis', points: 25 },
  { id: 'b20', cat: '⚽', label: 'Stå på höger ben i minst 1 minut', points: 20 },
  { id: 'b21', cat: '⚽', label: 'Stå på vänster ben i minst 1 minut', points: 20 },
  { id: 'b22', cat: '⚽', label: 'Gör plankan i 45 sekunder', points: 30 },
  { id: 'b23', cat: '⚽', label: 'Gör 10 benböj, 10 utfallssteg, 10 upphop', points: 30 },
  { id: 'b24', cat: '⚽', label: 'Jogga 2 km med en vuxen', points: 35 },
  { id: 'b25', cat: '⚽', label: 'Gör 10 kullerbyttor', points: 20 },
  { id: 'b26', cat: '⚽', label: 'Spela en match med andra', points: 40 },
  { id: 'b27', cat: '⚽', label: 'Lär dig en valfri fint', points: 25 },
  { id: 'b28', cat: '⚽', label: 'Testa att spela med bara ”fel fot” i 10 min', points: 30 },
  { id: 'b29', cat: '⚽', label: 'Öva på att kasta så långa inkast du kan 20 st', points: 30 },
  { id: 'b30', cat: '⚽', label: 'Gör 100 hopp med hopprep', points: 25 },
  { id: 'b31', cat: '⚽', label: 'Balansera bollen på foten i 10 sekunder', points: 35 },
  { id: 'b32', cat: '⚽', label: 'Spela fotboll barfota i gräs', points: 20 },
  {
    id: 'b33',
    cat: '⚽',
    label: 'Lär dig namn och position på 6 spelare i damlandslaget',
    points: 25,
  },
  { id: 'b34', cat: '⚽', label: 'Gå till Långholmens IP och spela fotboll', points: 30 },
  { id: 'b35', cat: '⚽', label: 'Träna fotboll mot en vägg i 30 minuter', points: 30 },
  // SOMMAR (15 st)
  { id: 'b36', cat: '☀️', label: 'Bada 3 gånger på en dag', points: 25 },
  { id: 'b37', cat: '☀️', label: 'Plocka ett strå med smultron', points: 20 },
  { id: 'b38', cat: '☀️', label: 'Plantera något (blomma, grönsak, frö…)', points: 25 },
  { id: 'b39', cat: '☀️', label: 'Läs en bok (minst 50 sidor)', points: 25 },
  { id: 'b40', cat: '☀️', label: 'Ät en glass', points: 15 },
  { id: 'b41', cat: '☀️', label: 'Cykla på en grusväg', points: 20 },
  { id: 'b42', cat: '☀️', label: 'Sov utomhus (tält, hängmatta, trappa…)', points: 30 },
  { id: 'b43', cat: '☀️', label: 'Bada på Långholmen', points: 15 },
  { id: 'b44', cat: '☀️', label: 'Hjälp till att laga mat', points: 20 },
  { id: 'b45', cat: '☀️', label: 'Skriv ett brev eller vykort till någon', points: 25 },
  { id: 'b46', cat: '☀️', label: 'Titta på solnedgången', points: 15 },
  { id: 'b47', cat: '☀️', label: 'Käka glass på Dello Sport', points: 20 },
  { id: 'b48', cat: '☀️', label: 'Laga mat eller baka något från grunden', points: 30 },
  { id: 'b49', cat: '☀️', label: 'Gör något snällt för någon utan att berätta det', points: 25 },
  { id: 'b50', cat: '☀️', label: 'Ha picknick utomhus', points: 20 },
];

export const ADULT_BINGO: BingoTile[] = [
  { id: 'ab01', label: 'Gör frukost på sängen åt ditt barn' },
  { id: 'ab02', label: 'Köp 2 glassar på samma dag' },
  { id: 'ab03', label: 'Spela fotboll tillsammans i minst 30 min' },
  { id: 'ab04', label: 'Jogga runt Långholmen tillsammans' },
  { id: 'ab05', label: 'Laga ditt barns favoritmat' },
  { id: 'ab06', label: 'Gör en mysig filmvisning med popcorn och dricka' },
  { id: 'ab07', label: 'Skriv ner 5 saker som ditt barn är bra på' },
  { id: 'ab08', label: 'Titta på en fotbollsmatch tillsammans' },
  { id: 'ab09', label: 'Ta en sommarbild tillsammans' },
  { id: 'ab10', label: 'Gör bomben nästa gång ni badar' },
  { id: 'ab11', label: 'Låt barnet bestämma en utflykt' },
  { id: 'ab12', label: 'Ta en skärgårdsbåt till Gällnö' },
  { id: 'ab13', label: 'Spela en match, dom vuxna mot barnen' },
  { id: 'ab14', label: 'Läs en bok för ditt barn när det regnar' },
  { id: 'ab15', label: 'Ät godis till middag, på riktigt!' },
  { id: 'ab16', label: 'Köp något litet överraskningsfika efter träningen' },
];

export const BONUS_BINGO: BingoTile[] = [
  { id: 'bb01', cat: '⚽', label: 'Skicka en kompisutmaning till någon i laget', points: 25 },
  { id: 'bb02', cat: '⚽', label: 'Träna tre dagar samma vecka', points: 30 },
  {
    id: 'bb03',
    cat: '⚽',
    label: 'Spela boll på en plats du aldrig spelat på tidigare',
    points: 25,
  },
  { id: 'bb04', cat: '⚽', label: 'Var först i laget att logga en dag', points: 25 },
  { id: 'bb05', cat: '⚽', label: 'Gör en egen hinderbana', points: 25 },
  { id: 'bb06', cat: '⚽', label: 'Spela fotboll i regnet', points: 25 },
  { id: 'bb07', cat: '⚽', label: 'Spela, träna eller lek en annan idrott i 30 min', points: 25 },
  { id: 'bb08', cat: '☀️', label: 'Lär dig ett nytt kortspel och spela med någon', points: 20 },
  { id: 'bb09', cat: '☀️', label: 'Testa en glassmak som du aldrig smakat', points: 15 },
  { id: 'bb10', cat: '☀️', label: 'Gör frukost på sängen till någon i din familj', points: 20 },
  { id: 'bb11', cat: '☀️', label: 'Läs ut en hel bok', points: 25 },
  { id: 'bb12', cat: '☀️', label: 'Chilla ute och lyssna på en ljudbok', points: 20 },
];

export const BINGO_TWO: BingoTile[] = [
  { id: 'b201', cat: '⚽', label: 'Träffa en kon eller flaska med bollen 10 gånger', points: 25 },
  {
    id: 'b202',
    cat: '⚽',
    label: 'Gör 15 passningar i rad med en kompis utan att bollen stannar',
    points: 25,
  },
  { id: 'b203', cat: '⚽', label: 'Dribbla en slalombana med bara vänster fot', points: 25 },
  { id: 'b204', cat: '⚽', label: 'Dribbla en slalombana med bara höger fot', points: 25 },
  {
    id: 'b205',
    cat: '⚽',
    label: 'Gör 10 chippassningar över en väska, kon eller pinne',
    points: 30,
  },
  { id: 'b206', cat: '⚽', label: 'Dribbla i en åtta runt två saker i 5 minuter', points: 25 },
  { id: 'b207', cat: '⚽', label: 'Försök träffa en flaska med inkast, öva i 10 min', points: 30 },
  { id: 'b208', cat: '⚽', label: 'Gör 10 skott direkt på rullande boll', points: 25 },
  { id: 'b209', cat: '⚽', label: 'Slå 10 passningar med utsidan av foten', points: 25 },
  {
    id: 'b210',
    cat: '⚽',
    label: 'Skjut från tre olika vinklar och gör mål från alla',
    points: 35,
  },
  { id: 'b211', cat: '⚽', label: 'Skjut 10 skott med första touch efter pass', points: 30 },
  {
    id: 'b212',
    cat: '⚽',
    label: 'Spela upp bollen mot vägg, vänd upp och skjut 10 gånger',
    points: 30,
  },
  {
    id: 'b213',
    cat: '⚽',
    label: 'Skjut 5 skott med vänster till valfritt mål och 5 med höger',
    points: 30,
  },
  { id: 'b214', cat: '⚽', label: 'Lär någon hemma vad offside betyder', points: 20 },
  { id: 'b215', cat: '⚽', label: 'Spela fotboll på planen i Tanto', points: 25 },
  {
    id: 'b216',
    cat: '⚽',
    label: 'Slå långa och höga passningar med någon annan i 10 min',
    points: 30,
  },
  { id: 'b217', cat: '⚽', label: 'Jonglera med bollen i 10 min, tre dagar i sträck', points: 40 },
  { id: 'b218', cat: '⚽', label: 'Jogga med boll runt en plan eller yta i 10 min', points: 25 },
  { id: 'b219', cat: '⚽', label: 'Gör målvaktsövningar med en kompis eller förälder', points: 30 },
  { id: 'b220', cat: '⚽', label: 'Försök stå på händer mot en vägg så länge du kan', points: 20 },
  { id: 'b221', cat: '⚽', label: 'Gör 20 situps', points: 20 },
  { id: 'b222', cat: '⚽', label: 'Gör 20 armhävningar', points: 25 },
  { id: 'b223', cat: '⚽', label: 'Gör 20 burpees', points: 30 },
  { id: 'b224', cat: '⚽', label: 'Spring baklänges 200 m', points: 25 },
  {
    id: 'b225',
    cat: '⚽',
    label: 'Hoppa jämfota så högt och långt du kan 20 + 20 gånger',
    points: 25,
  },
  {
    id: 'b226',
    cat: '⚽',
    label:
      'Skriv ner 3 olika lekar du vill leka på fotbollsträningen i höst, skicka till en ledare',
    points: 20,
  },
  {
    id: 'b227',
    cat: '⚽',
    label:
      'Skriv ner 3 olika övningar du vill köra på fotbollsträningen i höst, skicka till en ledare',
    points: 20,
  },
  {
    id: 'b228',
    cat: '⚽',
    label: 'Öva på att skydda bollen med kroppen mot en kompis, turas om',
    points: 30,
  },
  {
    id: 'b229',
    cat: '⚽',
    label: 'Utmana dig själv, hur länge kan du stå i jägarvila?',
    points: 20,
  },
  { id: 'b230', cat: '⚽', label: 'Träna på ett utegym', points: 25 },
  {
    id: 'b231',
    cat: '☀️',
    label: 'Gör en återhämtningskväll: stretch, vatten och tidig läggning',
    points: 20,
  },
  { id: 'b232', cat: '☀️', label: 'Ha picknick och ta med en boll', points: 20 },
  { id: 'b233', cat: '☀️', label: 'Gå en kvällspromenad med någon och prata fotboll', points: 15 },
  { id: 'b234', cat: '☀️', label: 'Skriv ner tre saker du vill lära dig i sommar', points: 15 },
  { id: 'b235', cat: '☀️', label: 'Rita en ny logga åt Högalid', points: 20 },
  {
    id: 'b236',
    cat: '☀️',
    label: 'Kom på en egen personlig hejaramsa åt 3 kompisar i laget',
    points: 20,
  },
  {
    id: 'b237',
    cat: '☀️',
    label: 'Ligg ner i gräset, blunda och fokusera på din andning i 10 min',
    points: 15,
  },
  { id: 'b238', cat: '☀️', label: 'Skriv en lista på 5 saker som du är bra på', points: 15 },
  { id: 'b239', cat: '☀️', label: 'Ta en hel dag utan någon form av skärm', points: 25 },
  { id: 'b240', cat: '☀️', label: 'Gå ut i naturen och hitta ett vilt djur', points: 20 },
  { id: 'b241', cat: '☀️', label: 'Plocka en bukett med blommor', points: 15 },
  { id: 'b242', cat: '☀️', label: 'Baka något gott och bjud någon', points: 20 },
  { id: 'b243', cat: '☀️', label: 'Ring någon du inte pratat med på länge', points: 15 },
  { id: 'b244', cat: '☀️', label: 'Gå en promenad i 30 min på morgonen före frukost', points: 20 },
  { id: 'b245', cat: '☀️', label: 'Läs en bok som en vuxen i din familj valt åt dig', points: 25 },
  { id: 'b246', cat: '☀️', label: 'Grilla marshmallows', points: 15 },
  { id: 'b247', cat: '☀️', label: 'Titta på stjärnorna', points: 15 },
  { id: 'b248', cat: '☀️', label: 'Lägg ett pussel med många bitar', points: 20 },
  { id: 'b249', cat: '☀️', label: 'Gå barfota en hel dag', points: 20 },
  { id: 'b250', cat: '☀️', label: 'Ha sovmorgon ända fram till lunch', points: 15 },
];

// Daily & Weekly Challenges
export const DAILY_CHALLENGES: DailyChallenge[] = [
  // Bollkontroll & teknik (30 st)
  { id: 'd01', label: 'Ta emot 20 kastade bollar med insidan av foten', points: 20, icon: '🦶' },
  { id: 'd02', label: 'Jonglera bollen 4 gånger utan att nudda marken', points: 20, icon: '⚽' },
  { id: 'd03', label: 'Gör 50 toe taps utan paus', points: 20, icon: '👟' },
  { id: 'd04', label: 'Håll bollen stilla på foten i 5 sekunder', points: 25, icon: '⚽' },
  { id: 'd05', label: 'Gör 25 tvåfotare utan att tappa bollen', points: 20, icon: '🦶' },
  { id: 'd06', label: 'Jonglera bollen 3 gånger med knät', points: 20, icon: '⚽' },
  {
    id: 'd07',
    label: 'Dribbla runt ett föremål 5 gånger med vänsterfoten',
    points: 20,
    icon: '🌀',
  },
  { id: 'd08', label: 'Gör 10 suldrag med höger och 10 med vänster fot', points: 20, icon: '👟' },
  { id: 'd09', label: 'Passa bollen mot en vägg i 15 minuter', points: 20, icon: '🏃' },
  {
    id: 'd10',
    label: 'Stoppa 20 bollar med sulan när någon rullar mot dig',
    points: 20,
    icon: '🦶',
  },
  { id: 'd11', label: 'Gör en Cruyff-fint 15 gånger i rad', points: 20, icon: '✨' },
  { id: 'd12', label: 'Ta emot 20 kastade bollar med knät', points: 20, icon: '⚽' },
  {
    id: 'd13',
    label: 'Skjut 20 skott och försök träffa ett mål eller en vägg',
    points: 20,
    icon: '🥅',
  },
  {
    id: 'd14',
    label: 'Dribla bollen med insidan fram och tillbaka 10 ggr',
    points: 20,
    icon: '🌀',
  },
  {
    id: 'd15',
    label: 'Driv bollen i en åtta runt två föremål i 3 minuter',
    points: 20,
    icon: '🌀',
  },
  {
    id: 'd16',
    label: 'Gör 10 vändningar med insidan och 10 med utsidan av foten',
    points: 20,
    icon: '👟',
  },
  {
    id: 'd17',
    label: 'Gör 15 passningar mot en vägg/kompis med ”fel” fot',
    points: 20,
    icon: '🏃',
  },
  { id: 'd18', label: 'Håll bollen i luften med axeln 3 gånger', points: 25, icon: '⚽' },
  { id: 'd19', label: 'Gör 20 toe taps med enbart vänsterfoten', points: 20, icon: '👟' },
  {
    id: 'd20',
    label: 'Kasta/skjut bollen mot en vägg och ta emot med bröstet',
    points: 25,
    icon: '🏃',
  },
  { id: 'd21', label: 'Stå på ett ben så länge du kan!', points: 20, icon: '🦶' },
  { id: 'd22', label: 'Gör en fint och skjut — 5 gånger', points: 20, icon: '🥅' },
  {
    id: 'd23',
    label: 'Gör en hinderbana och dribbla runt utan att tappa bollen',
    points: 20,
    icon: '🌀',
  },
  { id: 'd24', label: 'Jonglera bollen 2 gånger med huvudet', points: 25, icon: '⚽' },
  {
    id: 'd25',
    label: 'Gör 25 passningar med insidan av foten mot en vägg',
    points: 20,
    icon: '🏃',
  },
  { id: 'd26', label: 'Skjut 20 skott och försök träffa i ett hörn', points: 25, icon: '🥅' },
  {
    id: 'd27',
    label: 'Kasta upp bollen högt och ta emot den med foten 10 gånger',
    points: 20,
    icon: '⚽',
  },
  {
    id: 'd28',
    label: 'Passa 30 gånger mot vägg utan att bollen stannar helt',
    points: 20,
    icon: '🏃',
  },
  { id: 'd29', label: 'Spela Rondo med 4 andra', points: 30, icon: '🤝' },
  { id: 'd30', label: 'Balansera bollen på foten och gå 3 steg', points: 30, icon: '⚽' },
  // Kondition & rörlighet (20 st)
  { id: 'd31', label: 'Gå ut och spring så långt du orkar', points: 20, icon: '🏃' },
  { id: 'd32', label: 'Gör 15 utfallssteg med bollen i händerna', points: 20, icon: '💪' },
  { id: 'd33', label: 'Hoppa hopprep i 1 minut', points: 20, icon: '💫' },
  { id: 'd34', label: 'Gör 10 benböj och 10 armhävningar', points: 20, icon: '💪' },
  { id: 'd35', label: 'Stå i plankan i 30 sekunder', points: 20, icon: '💪' },
  { id: 'd36', label: 'Gör 20 höga knän på stället i 30 sekunder', points: 20, icon: '🏃' },
  { id: 'd37', label: 'Stretcha benen ordentligt i 5 minuter', points: 15, icon: '🧘' },
  { id: 'd38', label: 'Gör 10 kullerbyttor', points: 15, icon: '🌀' },
  {
    id: 'd39',
    label: 'Stå på ett ben i 45 sekunder utan att nudda marken',
    points: 20,
    icon: '🦶',
  },
  { id: 'd40', label: 'Gör 20 hopp på ett ben — höger och vänster', points: 20, icon: '💫' },
  { id: 'd41', label: 'Gör 10 situps, tre gånger!', points: 20, icon: '💪' },
  { id: 'd42', label: 'Gör 15 armhävningar', points: 20, icon: '💪' },
  { id: 'd43', label: 'Hitta en backe och spring upp, gå ner, 10 ggr', points: 35, icon: '🏃' },
  { id: 'd44', label: 'Gör 30 jumping jacks', points: 15, icon: '💫' },
  {
    id: 'd45',
    label: 'Spring baklänges fram och tillbaka över en fotbollsplan, 6 ggr',
    points: 25,
    icon: '🏃',
  },
  { id: 'd46', label: 'Gör 10 utfallssteg framåt och 10 bakåt', points: 20, icon: '💪' },
  {
    id: 'd47',
    label: 'Hoppa över ett föremål, fram och tillbaka 20 gånger',
    points: 20,
    icon: '💫',
  },
  { id: 'd48', label: 'Balansera på ett ben med ögonen stängda i 20 sek', points: 25, icon: '🧘' },
  {
    id: 'd49',
    label: 'Gör 5 minuters uppvärmning: springa, hopp och stretch',
    points: 20,
    icon: '🏃',
  },
  {
    id: 'd50',
    label: 'Ta en 10-minuters promenad med fotbollen under armen',
    points: 15,
    icon: '🌿',
  },
  // Roliga/kreativa (20 st)
  { id: 'd51', label: 'Hitta på ett eget tricks och visa det för någon', points: 25, icon: '🌟' },
  { id: 'd52', label: 'Spela fotboll barfota på gräs', points: 20, icon: '🌿' },
  { id: 'd53', label: 'Öva in en målgest', points: 15, icon: '🎉' },
  { id: 'd54', label: 'Sjung lagets hejaramsa högt tre gånger', points: 15, icon: '📣' },
  { id: 'd55', label: 'Spela fotboll med någon du inte känner', points: 25, icon: '🤝' },
  { id: 'd56', label: 'Skjut en straff med ögonen stängda', points: 25, icon: '🥅' },
  { id: 'd57', label: 'Skapa en hinderbana och dribbla igenom den', points: 20, icon: '🌀' },
  { id: 'd58', label: 'Träna med någon annan i 15 minuter', points: 20, icon: '🤝' },
  { id: 'd59', label: 'Filma dig själv och titta på en övning du gjort', points: 20, icon: '📱' },
  { id: 'd60', label: 'Berätta för någon vad du tränat idag', points: 15, icon: '💬' },
  {
    id: 'd61',
    label: 'Sätt upp ett mål för nästa säsong och skriv ned det',
    points: 15,
    icon: '📝',
  },
  { id: 'd62', label: 'Prova att jonglera med en tennisboll', points: 25, icon: '⚽' },
  { id: 'd63', label: 'Spela fotboll mot en vägg i 10 minuter', points: 20, icon: '🏃' },
  {
    id: 'd64',
    label: 'Passa med någon och se hur många passningar ni kan slå utan att tappa bollen',
    points: 20,
    icon: '🤝',
  },
  { id: 'd65', label: 'Lek kasta gris med någon/några andra', points: 20, icon: '🎯' },
  { id: 'd66', label: 'Lek ”håll den uppe” med en ballong inomhus', points: 15, icon: '🎈' },
  { id: 'd67', label: 'Ta 10 foton av din boll på roliga ställen', points: 15, icon: '📸' },
  {
    id: 'd68',
    label: 'Hitta på en ny övning och lär ut den till en vuxen',
    points: 25,
    icon: '💡',
  },
  { id: 'd69', label: 'Gör 10 skott med höger och 10 med vänsterfoten', points: 20, icon: '🥅' },
  { id: 'd70', label: 'Öva på att göra en ”Rainbow flick” i 20 min', points: 30, icon: '🌈' },
];

// Weekly challenges — team goals based on week number
// Each week alternates between touch-heavy and minutes-heavy
export const WEEKLY_CHALLENGES: WeeklyChallenge[] = [
  {
    id: 'w01',
    label: 'Jonas utmanar er: 2800 touch tillsammans den här veckan',
    type: 'touch',
    goal: 2800,
    points: 50,
  },
  {
    id: 'w02',
    label: '190 minuters träning tillsammans den här veckan',
    type: 'minutes',
    goal: 190,
    points: 50,
  },
  {
    id: 'w03',
    label: 'Calle utmanar er: 3000 touch tillsammans den här veckan',
    type: 'touch',
    goal: 3000,
    points: 60,
  },
  {
    id: 'w04',
    label: '210 minuters träning tillsammans den här veckan',
    type: 'minutes',
    goal: 210,
    points: 60,
  },
  {
    id: 'w05',
    label: 'Jakob utmanar er: 3200 touch tillsammans den här veckan',
    type: 'touch',
    goal: 3200,
    points: 70,
  },
  {
    id: 'w06',
    label: '230 minuters träning tillsammans den här veckan',
    type: 'minutes',
    goal: 230,
    points: 70,
  },
  {
    id: 'w07',
    label: 'Richard utmanar er: 3400 touch tillsammans den här veckan',
    type: 'touch',
    goal: 3400,
    points: 75,
  },
  {
    id: 'w08',
    label: '250 minuters träning tillsammans den här veckan',
    type: 'minutes',
    goal: 250,
    points: 75,
  },
  {
    id: 'w09',
    label: 'Peter utmanar er: 3600 touch tillsammans den här veckan',
    type: 'touch',
    goal: 3600,
    points: 80,
  },
  {
    id: 'w10',
    label: '270 minuters träning tillsammans den här veckan',
    type: 'minutes',
    goal: 270,
    points: 80,
  },
  {
    id: 'w11',
    label: 'Jonas utmanar er igen: 3800 touch tillsammans den här veckan',
    type: 'touch',
    goal: 3800,
    points: 90,
  },
  {
    id: 'w12',
    label: '290 minuters träning tillsammans den här veckan',
    type: 'minutes',
    goal: 290,
    points: 90,
  },
];
