import type { Sticker } from '../types';

export const STICKERS: Sticker[] = [
  {
    id: 'start_shot',
    label: 'Startskottet',
    icon: '🚀',
    group: 'Start & Vecka',
    description: 'Logga din första träning',
  },
  {
    id: 'monday_starter',
    label: 'Måndagsstart',
    icon: '📅',
    group: 'Start & Vecka',
    description: 'Träna en måndag',
  },
  {
    id: 'tuesday_touch',
    label: 'Tisdagstouch',
    icon: '👟',
    group: 'Start & Vecka',
    description: 'Träna en tisdag',
  },
  {
    id: 'wednesday_warrior',
    label: 'Onsdagskämpe',
    icon: '🛡️',
    group: 'Start & Vecka',
    description: 'Träna en onsdag',
  },
  {
    id: 'first_thursday',
    label: 'Första torsdagen',
    icon: '✨',
    group: 'Start & Vecka',
    description: 'Träna en torsdag',
  },
  {
    id: 'friday_focus',
    label: 'Fredagsfokus',
    icon: '🎯',
    group: 'Start & Vecka',
    description: 'Träna en fredag',
  },
  {
    id: 'saturday_smile',
    label: 'Lördagslir',
    icon: '😎',
    group: 'Start & Vecka',
    description: 'Träna en lördag',
  },
  {
    id: 'sunday_hero',
    label: 'Söndagshjälte',
    icon: '🌅',
    group: 'Start & Vecka',
    description: 'Träna en söndag',
  },
  {
    id: 'week_three_logs',
    label: 'Tre pass samma vecka',
    icon: '🗓️',
    group: 'Start & Vecka',
    description: 'Logga 3 träningsdagar under samma vecka',
  },
  {
    id: 'week_five_logs',
    label: 'Fem pass samma vecka',
    icon: '💥',
    group: 'Start & Vecka',
    description: 'Logga 5 träningsdagar under samma vecka',
  },
  {
    id: 'not_reymers',
    label: 'Hejar inte på Reymers!',
    icon: '😮‍💨',
    group: 'Start & Vecka',
    description: 'Var först i laget med att logga en träningsdag',
  },
  {
    id: 'streak2',
    label: 'Två dagar i rad',
    icon: '🔥',
    group: 'Start & Vecka',
    description: 'Håll en streak i 2 dagar',
  },
  {
    id: 'streak3',
    label: 'Tre dagar i rad',
    icon: '⚡',
    group: 'Start & Vecka',
    description: 'Håll en streak i 3 dagar',
  },
  {
    id: 'first_daily',
    label: 'Första dagsuppdraget',
    icon: '✅',
    group: 'Start & Vecka',
    description: 'Klara ditt första dagsuppdrag',
  },
  {
    id: 'three_dailies',
    label: 'Trippeluppdrag',
    icon: '🌟',
    group: 'Start & Vecka',
    description: 'Klara 3 dagsuppdrag',
  },
  {
    id: 'five_dailies',
    label: 'Fem uppdrag klara',
    icon: '🏁',
    group: 'Start & Vecka',
    description: 'Klara 5 dagsuppdrag',
  },

  {
    id: 'toetaps_friend',
    label: 'Toe taps-start',
    icon: '⚽',
    group: 'Övningar',
    description: 'Logga toe taps första gången',
  },
  {
    id: 'twofoot_friend',
    label: 'Tvåfotarvän',
    icon: '🦶',
    group: 'Övningar',
    description: 'Logga tvåfotare första gången',
  },
  {
    id: 'cruyff_friend',
    label: 'Cruyff-kompis',
    icon: '🌀',
    group: 'Övningar',
    description: 'Logga Cruyff-fint första gången',
  },
  {
    id: 'juggle_friend',
    label: 'Jonglervän',
    icon: '🎪',
    group: 'Övningar',
    description: 'Logga jonglering första gången',
  },
  {
    id: 'passing_friend',
    label: 'Passningshumör',
    icon: '🪄',
    group: 'Övningar',
    description: 'Logga passningar första gången',
  },
  {
    id: 'shot_happy',
    label: 'Skottglad',
    icon: '🥅',
    group: 'Övningar',
    description: 'Logga skott första gången',
  },
  {
    id: 'free_training_20',
    label: 'Fri träningsglöd',
    icon: '⏱️',
    group: 'Övningar',
    description: 'Logga 20 minuter fri träning i ett pass',
  },
  {
    id: 'toetaps_100',
    label: '100 toe taps',
    icon: '👣',
    group: 'Övningar',
    description: 'Gör 100 toe taps i ett pass',
  },
  {
    id: 'twofoot_100',
    label: '100 tvåfotare',
    icon: '🦶',
    group: 'Övningar',
    description: 'Gör 100 tvåfotare i ett pass',
  },
  {
    id: 'shot_ten',
    label: '10 skott',
    icon: '💥',
    group: 'Övningar',
    description: 'Skjut 10 skott i ett pass',
  },
  {
    id: 'cruyff_three_days',
    label: 'Cruyff-flow',
    icon: '💫',
    group: 'Övningar',
    description: 'Logga Cruyff-fint på 3 olika dagar',
  },
  {
    id: 'juggle_three_days',
    label: 'Jongleringsflow',
    icon: '🌈',
    group: 'Övningar',
    description: 'Logga jonglering på 3 olika dagar',
  },
  {
    id: 'passing_three_days',
    label: 'Passningsflow',
    icon: '📬',
    group: 'Övningar',
    description: 'Logga passningar på 3 olika dagar',
  },
  {
    id: 'shot_three_days',
    label: 'Skottflow',
    icon: '🚀',
    group: 'Övningar',
    description: 'Logga skott på 3 olika dagar',
  },

  {
    id: 'bingo_start',
    label: 'Bingostart',
    icon: '🎲',
    group: 'Bingo & Foto',
    description: 'Klara din första bingoruta',
  },
  {
    id: 'bingo_five',
    label: 'Fem bingorutor',
    icon: '🟩',
    group: 'Bingo & Foto',
    description: 'Klara 5 bingorutor',
  },
  {
    id: 'photographer',
    label: 'Fotografen',
    icon: '📸',
    group: 'Bingo & Foto',
    description: 'Ladda upp din första bild i albumet',
  },
  {
    id: 'album_friend',
    label: 'Albumkompis',
    icon: '🖼️',
    group: 'Bingo & Foto',
    description: 'Ladda upp 3 bilder i albumet',
  },
  {
    id: 'master_photographer',
    label: 'Mästerfotograf',
    icon: '📷',
    group: 'Bingo & Foto',
    description: 'Ladda upp 5 bilder i albumet',
  },
  {
    id: 'secret_adult_bingo',
    label: 'Hemligt vuxenbingo',
    icon: '🕵️',
    group: 'Hemligt & Bonus',
    description: 'Hitta Hemligt vuxenbingo',
  },
  {
    id: 'secret_penalty_game',
    label: 'Hittade straffspelet',
    icon: '🎯',
    group: 'Hemligt & Bonus',
    description: 'Hitta det hemliga straffspelet',
  },
  {
    id: 'secret_both_found',
    label: 'Båda hemligheterna',
    icon: '🥚',
    group: 'Hemligt & Bonus',
    description: 'Hitta båda easter eggs i appen',
  },
  {
    id: 'secret_adult_line',
    label: 'Vuxenbingo!',
    icon: '🎉',
    group: 'Hemligt & Bonus',
    description: 'Få bingo i Hemligt vuxenbingo',
  },
  {
    id: 'secret_penalty_eight',
    label: '8 mål i straffarna',
    icon: '🥇',
    group: 'Hemligt & Bonus',
    description: 'Gör 8 eller fler mål i straffspelet',
  },

  {
    id: 'buddy_first',
    label: 'Första kompisutmaningen',
    icon: '🤝',
    group: 'Kompis & Sommar',
    description: 'Klara en kompisutmaning',
  },
  {
    id: 'buddy_triple',
    label: 'Kompisflow',
    icon: '💪',
    group: 'Kompis & Sommar',
    description: 'Klara 3 kompisutmaningar',
  },
  {
    id: 'summer_start',
    label: 'Sommargrejs-start',
    icon: '🍉',
    group: 'Kompis & Sommar',
    description: 'Logga första sommargrejen',
  },
  {
    id: 'icecream_day',
    label: 'Glassdag',
    icon: '🍦',
    group: 'Kompis & Sommar',
    description: 'Logga glass i sommargrejer',
  },
  {
    id: 'swim_day',
    label: 'Baddag',
    icon: '🏊',
    group: 'Kompis & Sommar',
    description: 'Logga bad i sommargrejer',
  },
  {
    id: 'reading_day',
    label: 'Läsdag',
    icon: '📖',
    group: 'Kompis & Sommar',
    description: 'Logga läsning i sommargrejer',
  },
  {
    id: 'icecream_three',
    label: 'Glass i solen',
    icon: '🍨',
    group: 'Kompis & Sommar',
    description: 'Logga glass 3 gånger',
  },
  {
    id: 'swim_three',
    label: 'Vattenvän',
    icon: '🌊',
    group: 'Kompis & Sommar',
    description: 'Logga bad 3 gånger',
  },
  {
    id: 'reading_thirty',
    label: 'Bokslukare',
    icon: '📚',
    group: 'Kompis & Sommar',
    description: 'Läs 30 sidor totalt',
  },
  {
    id: 'summer_triple_week',
    label: 'Sommartrippel',
    icon: '🌴',
    group: 'Kompis & Sommar',
    description: 'Logga 3 sommargrejer samma vecka',
  },
  {
    id: 'summer_allrounder',
    label: 'Sommarallrounder',
    icon: '🌺',
    group: 'Kompis & Sommar',
    description: 'Logga glass, bad och läsning',
  },
];

export const STICKER_GROUPS: string[] = [
  'Start & Vecka',
  'Övningar',
  'Bingo & Foto',
  'Hemligt & Bonus',
  'Kompis & Sommar',
];
